baseURL = 'https://etvon.github.io/CUBE/'
languageCode = 'en-us'
title = 'eWeLink CUBE'
theme = 'hugo-theme-relearn'
[params]
  themeVariant = 'blue'
[outputs]
  home = ['html', 'rss', 'search', 'searchpage']